### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kokoro-kusakabe** [kokoro-kusakabe/protospace-30573#1]
Protospaceの挙動確認をお願いします。
herokuURL
https://protospace-30573.herokuapp.com/

**Comment by hiraoka1102** [comment]
両角さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
